[package]
name = "rotmguard"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ctrlc = "3.4.4"
hex = "0.4.3"
iptables = "0.5.1"
nix = { version = "0.29.0", features = ["socket", "net"] }
rand = "0.8.5"
rc4 = "0.1.0"
tokio = { version = "1.37.0", features = ["full"] }
