# A path to the game's resources.assets.
# Look in your proton pfx, it can usually be found in somewhere like
# C:/users/steamuser/Documents/RealmOfTheMadGod/Production/RotMG Exalt_Data/
#
# Proton pfx can be found in ~/.steam/root/steamapps/compatdata/<app id>/pfx/
# To find the `app id` of your game, in Steam library right click on it -> properties -> Updates
assets_res = "/home/mykolas/.steam/root/steamapps/compatdata/200210/pfx/drive_c/users/steamuser/Documents/RealmOfTheMadGod/Production/RotMG Exalt_Data/resources.assets"

[settings]
autonexus_hp = 0
dev_mode = false
log_lines = 1000

# True = debuff disabled
[settings.debuffs]
blind = true
hallucinating = true
drunk = true
confused = true
unstable = true
darkness = false # you still dont see very far so disabling this doesnt help, all it does it make you not know when the effect is actually over

# The following will edit game resource files, you will need to launch the game AFTER rotmguard is already running
# for these to work.
[settings.edit_assets]
enabled = true
# If true, will remove the client-side debuffs completely
force_debuffs = true