# A path to the game's resources.assets.
# Look in your proton pfx, it can usually be found in somewhere like
# C:/users/steamuser/Documents/RealmOfTheMadGod/Production/RotMG Exalt_Data/
#
# Proton pfx can be found in ~/.steam/root/steamapps/compatdata/<app id>/pfx/
# To find the `app id` of your game, in Steam library right click on it -> properties -> Updates
assets_res = "/home/mykolas/.steam/root/steamapps/compatdata/200210/pfx/drive_c/users/steamuser/Documents/RealmOfTheMadGod/Production/RotMG Exalt_Data/resources.assets"

[settings]
# HP below which (not AT which) to autonexus. Recommended value 20
autonexus_hp = 1
# Enables damage monitoring, see stats with /dmg command
damage_monitor = true
# Reduces lag by blocking certain packets
antilag = true
# If true, will activate developer mode.
dev_mode = false
# Whether to attempt to automatically open damage monitor links in the browser
# most likely you want to leave this on
open_browser = true

# True = debuff disabled
[settings.debuffs]
blind = true
hallucinating = true
drunk = true
confused = true
hexed = true
unstable = true
darkness = false # you still dont see very far so disabling this doesnt help, all it does it make you not know when the effect is actually over

# The following will edit game resource files, you will need to launch the game
# (not the launcher, only the game itself) AFTER rotmguard is already running
# for these to work.
[settings.edit_assets]
enabled = true
# If true, will remove the client-side debuffs completely
force_debuffs = true
